---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chengzhiwei.
--- DateTime: 2022/5/12 12:00 上午
---
function fact(n)
    if n == 0 then
        return 1
    else
        return n * fact(n - 1)
    end
end

print("enter a number:")
a = io.read("*n")   -- 读取一个数字
print(fact(a))