---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chengzhiwei.
--- DateTime: 2022/5/12 11:02 上午
---
print(type(nil)) -- nil
print(type(true)) -- boolean
print(type(10))  -- number
print(type("Hello World")) -- string
print(type(io.stdin))  -- userdata
print(type(print))   -- function
print(type(coroutine.create(function() print("hi") end)))    -- thread
print(type({}))  -- table
print(type(type(X)))  -- string