---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chengzhiwei.
--- DateTime: 2022/5/12 11:49 上午
---
print(string.rep("abc", 3)) -- abcabcabc
print(string.reverse("A Long Line!")) -- !eniL gnoL A
print(string.lower("A Long Line")) -- a long line

-- 字符串的第一个字符索引是 1，并且是前后都闭合 []
s = "[in brackets]"
print(string.sub(s, 2, -2)) -- in brackets
print(string.sub(s, 1, 1)) -- [
print(string.sub(s, -1, -1)) -- ]


-- 格式化
print(string.format("x = %d, y = %d", 10, 20))  -- x = 10, y = 20

-- 冒号操作符
s = "good"
S = s:sub(1,2) -- go
print(S)